Repository UniGrazMath/vitabel, pull requests merged in 2025-03, with the labels that each got.

#42 Improve robustness of loading ZOLL-json format
  src/vitabel/timeseries.py
  src/vitabel/utils/loading.py
Labels: bug

#40 Update README.md
  README.md
Labels: documentation

#44 Update stylesheet.py for Bedmaster at CHOP
  src/vitabel/utils/stylesheet.py
Labels: enhancement

#47 patched plotting routine of IntervalLabels as Rectangle
  src/vitabel/timeseries.py
Labels: bug
