Repository UniGrazMath/vitabel, pull requests merged in 2025-06, with the labels that each got.

#113 Basic support: allow None / pandas.NaT / numpy.nan in time_index
  src/vitabel/timeseries.py
  tests/test_timeseries.py
Labels: enhancement

#164 refactor find_CC_periods to return IntervalLabel
  src/vitabel/utils/stylesheet.py
  src/vitabel/vitals.py
  tests/test_vitals.py
Labels: enhancement

#165 added Label for etco2
  src/vitabel/utils/stylesheet.py
Labels: c:plotting

#170 Fix IntervalLabel.from_dict to ignore vline_text_source and other irr…
  src/vitabel/timeseries.py
  tests/test_timeseries.py
Labels: bug, c:data loading

#166 legend multiple times given for axvspan
  src/vitabel/timeseries.py
Labels: bug, c:plotting

#175 Refactor input to `area_under_threshold` in form of new `source` argument
  src/vitabel/timeseries.py
  src/vitabel/vitals.py
  tests/test_vitals.py
Labels: enhancement

#182 Fix repainting of overview indicators after changes to overview plot
  src/vitabel/timeseries.py
Labels: bug

#184 Add auxiliary data structure `DataSlice` holding the output of `Channel.get_data` / `Label.get_data`
  src/vitabel/timeseries.py
  src/vitabel/typing.py
  src/vitabel/vitals.py
  tests/test_timeseries.py
  tests/test_vitals.py
Labels: enhancement

#189 Fix: make sure shift marker is redrawn when interactive plot is repainted
  src/vitabel/timeseries.py
Labels: bug

#192 Include adjacent non-included data points when plotting to avoid plots breaking at the ends
  src/vitabel/timeseries.py
  tests/data/test_channel_plot_absolute_time.png
  tests/data/test_channel_plot_no_data.png
Labels: enhancement

#202 enhancement: added unpacking of array of tuples of times as time_inde…
  src/vitabel/timeseries.py
  tests/test_timeseries.py
Labels: enhancement, c:data structure

#209 harmonizations channel label operations, especially adding filtering
  src/vitabel/timeseries.py
  src/vitabel/vitals.py
  tests/test_timeseries.py
Labels: documentation, enhancement

#212 feature: Add rename method to Label class for updating label names
  src/vitabel/timeseries.py
Labels: c:data structure

#231 Include demo notebooks as statically rendered subpages in documentation
  docs/source/conf.py
  docs/source/examples
  docs/source/examples.md
  docs/source/index.md
  pyproject.toml
  uv.lock
Labels: documentation
