Repository UniGrazMath/vitabel, pull requests merged in 2025-05, with the labels that each got.

#68 Fix #67 - UFuncTypeError
  src/vitabel/timeseries.py
Labels: bug

#86 bugfix wrong call
  src/vitabel/vitals.py
Labels: bug

#87 Update vitals.py
  src/vitabel/vitals.py
Labels: bug

#97 improve documentation
  docs/source/_static/css/extra.css
  docs/source/_static/img/vitabel-demo.png
  docs/source/_static/logo/logo.svg
  docs/source/conf.py
  docs/source/development.md
  docs/source/index.md
  docs/source/quickstart.md
Labels: documentation

#102 Enhancement/99 importer dataclasses
  src/vitabel/vitals.py
  tests/test_vitals.py
Labels: bug, enhancement, c:data loading

#104 various improvements to csv / data frame loading code
  src/vitabel/vitals.py
Labels: enhancement

#77 Implemntation of Feature Request #4 - TWA MAP
  .gitignore
  src/vitabel/timeseries.py
  src/vitabel/typing.py
  src/vitabel/utils/helpers.py
  src/vitabel/vitals.py
  tests/test_vitals.py
Labels: enhancement

#106 Add library version to exported data and check for version mismatch when loading
  src/vitabel/__init__.py
  src/vitabel/vitals.py
  tests/test_vitals.py
Labels: enhancement, c:data loading

#111 Fix and improve handling of time offset, allow directly setting offset attribute
  src/vitabel/timeseries.py
  tests/test_timeseries.py
  tests/test_vitals.py
Labels: bug
